export const testIds = {
  homePage: 'home-page',
  doctorListPage: 'doctor-list-page',
  doctorCard: 'doctor-card',
  doctorDetailPage: 'doctor-detail-page',
  doctorDetailLink: 'doctor-detail-link',
  bookAppointmentGuest: 'book-appointment-guest',
  loginPage: 'login-page',
  registerPage: 'register-page',
  patientDashboardPage: 'patient-dashboard-page',
  appointmentCreatePage: 'appointment-create-page',
  appointmentListPage: 'appointment-list-page',
  questionCreatePage: 'question-create-page',
  doctorDashboardPage: 'doctor-dashboard-page',
  doctorQuestionListPage: 'doctor-question-list-page',
  doctorAnswerForm: 'doctor-answer-form',
  adminDashboardPage: 'admin-dashboard-page',
  adminDoctorListPage: 'admin-doctor-list-page',
  forbiddenPage: 'forbidden-page',
  loadingState: 'loading-state',
  emptyState: 'empty-state',
  errorAlert: 'error-alert',
};
